openai_api_key:
openrouter_api_key:
telegram_api_id:
telegram_api_hash:
google_app_id:
debug_copilot: false
dev_mode: false
host_name: "localhost"
port: 8123
uploads_dir: "/tmp"
prompts_dir: "./configs"
