model_connection_api_key:
model_connection_api_base_url:
telegram_api_id:
telegram_api_hash:
google_app_id:
debug_copilot: false
dev_mode: false
use_webview: false
host_name: "localhost"
port: 20770
uploads_dir: "/tmp"
