openai_api_key:
openai_base_url:
openrouter_api_key:
telegram_api_id:
telegram_api_hash:
google_app_id:
debug_copilot: false
dev_mode: false
use_webview: false
host_name: "localhost"
port: 20770
uploads_dir: "/tmp"
